In [ ]:
import pandas as pd
df = pd.read_csv("datos_casas_india.csv")

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
mascara = df["price"] >=10000

df_mayores = df[mascara]
df_mayores

,house_type,house_size,location,city,latitude,longitude,price,currency,numBathrooms,numBalconies,isNegotiable,priceSqFt,verificationDate,description,SecurityDeposit,Status
0,1 RK Studio Apartment,400 sq ft,Kalkaji,Delhi,28.545561,77.254349,22000,INR,1.0,NaN,NaN,NaN,Posted a day ago,"Fully furnished, loaded with amenities & gadge...",No Deposit,Furnished
1,1 RK Studio Apartment,400 sq ft,Mansarover Garden,Delhi,28.643259,77.132828,20000,INR,1.0,NaN,NaN,NaN,Posted 9 days ago,Here is an excellent 1 BHK Independent Floor a...,No Deposit,Furnished
3,3 BHK Independent House,"1,020 sq ft",Model Town,Delhi,28.712898,77.180000,48000,INR,3.0,NaN,NaN,NaN,Posted a year ago,Itâs a 3 bhk independent house situated in M...,No Deposit,Furnished
4,2 BHK Apartment,810 sq ft,Sector 13 Rohini,Delhi,28.723539,77.131424,20000,INR,2.0,NaN,NaN,NaN,Posted a year ago,Well designed 2 bhk multistorey apartment is a...,No Deposit,Unfurnished
5,3 BHK Apartment,750 sq ft,DLF Farms,Delhi,28.488153,77.156975,11000,INR,1.0,NaN,NaN,NaN,Posted 2 years ago,Well designed 3 bhk multistorey apartment is a...,No Deposit,Semi-Furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4 BHK Villa,"5,896 sq ft",Sunder Nagar,Delhi,28.618437,76.961784,1022001,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,Its four bhk villa in the super location of De...,"40,10,102",Unfurnished
4996,5 BHK Independent House,"6,521 sq ft",Sunder Nagar,Delhi,28.618437,76.961784,1549181,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,A 5 bhk property is available for rent in Sund...,"54,01,015",Unfurnished
4997,3 BHK Independent Floor,"1,855 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301012,INR,3.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"18,18,181",Unfurnished
4998,3 BHK Independent Floor,"2,856 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301011,INR,3.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"10,10,110",Unfurnished
4999,3 BHK Independent Floor,"2,856 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301012,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"10,10,182",Unfurnished

In [ ]:
menores_10000= df[df["price"]>=10000]
len(menores_10000)

4827

In [ ]:
df_mayores = df[df["price"]>=10000]

In [ ]:
df_mayores.info()
df_mayores.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 4827 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   house_type        4827 non-null   object
 1   house_size        4827 non-null   object
 2   location          4827 non-null   object
 3   city              4827 non-null   object
 4   latitude          4827 non-null   float64
 5   longitude         4827 non-null   float64
 6   price             4827 non-null   int64
 7   currency          4827 non-null   object
 8   numBathrooms      4802 non-null   float64
 9   numBalconies      2701 non-null   float64
 10  isNegotiable      171 non-null    object
 11  priceSqFt         0 non-null      float64
 12  verificationDate  4827 non-null   object
 13  description       4545 non-null   object
 14  SecurityDeposit   4827 non-null   object
 15  Status            4827 non-null   object
dtypes: float64(5), int64(1), object(10)
memory usage: 641.1+ KB

,latitude,longitude,price,numBathrooms,numBalconies,priceSqFt
count,4827.000000,4827.000000,4.827000e+03,4802.000000,2701.000000,0.0
mean,28.576911,77.176751,2.298642e+05,2.981883,1.962606,NaN
std,0.193132,0.116145,2.757692e+05,1.051420,0.542704,NaN
min,20.011379,72.771332,1.000000e+04,1.000000,1.000000,NaN
25%,28.544250,77.141388,3.200000e+04,2.000000,2.000000,NaN
50%,28.568350,77.199554,1.500000e+05,3.000000,2.000000,NaN
75%,28.618437,77.229736,3.046565e+05,4.000000,2.000000,NaN
max,28.805466,80.361313,3.010101e+06,10.000000,8.000000,NaN

In [ ]:
serie_location = df_mayores["location"]
serie_location

0                  Kalkaji
1        Mansarover Garden
3               Model Town
4         Sector 13 Rohini
5                DLF Farms
               ...
4995          Sunder Nagar
4996          Sunder Nagar
4997    New Friends Colony
4998    New Friends Colony
4999    New Friends Colony
Name: location, Length: 4827, dtype: object